# Generated by Django 5.2.1 on 2025-05-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                (
                    "authors",
                    models.CharField(
                        help_text="姓 名, …", max_length=200, verbose_name="著者"
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="出版年"
                    ),
                ),
                (
                    "journal",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="雑誌 / 会議名"
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "pdf",
                    models.FileField(blank=True, upload_to="pdfs/", verbose_name="PDF"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
