# Generated by Django 5.2.1 on 2025-05-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="memo",
            field=models.TextField(blank=True, verbose_name="メモ（Markdown）"),
        ),
    ]
