# Generated by Django 5.2.1 on 2025-05-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_category_tag_reference_category_reference_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="progress",
            field=models.CharField(
                choices=[
                    ("not_started", "未読"),
                    ("in_progress", "途中まで読んだ"),
                    ("done", "読了"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
