# Generated by Django 5.2.1 on 2025-05-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_reference_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="pdf_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
